/* `components/index.js` ia a 'central export' for our components. */

export {Login, Signup} from './auth-form'
export {default as UserHome} from './user-home'
export {default as Nav} from './Nav'
export {default as Artists} from './Artists'
export {default as ArtistDetail} from './ArtistDetail'
export {default as Catalogs} from './Catalogs'
export {default as Home} from './Home'
export {default as Footer} from './Footer'
export {default as Category} from './Category'
export {default as Contact} from './Contact'
export {default as SearchBar} from './search'
export {default as AllProducts} from './AllProducts'
export {default as ProductDetail} from './ProductDetail'
export {default as SingleProduct} from './SingleProduct'
export {default as AdminToolbar} from './AdminToolbar'
export {default as AdminAddProduct} from './Admin-AddProduct'
export {default as AdminAddArtist} from './Admin-AddArtist'
export {default as Carousel} from './Carousel'
export {default as Construction} from './Construction'
export {default as AllUsers} from './AllUsers'
export {default as ResetPassword} from './ResetPassword'
export {default as ResetPasswordPage} from './ResetPasswordPage'
export {default as AdminArtistQuicklist} from './Admin-ArtistQuicklist'
export {default as AdminProductQuicklist} from './Admin-ProductQuicklist'
